from pydantic import BaseModel
from datetime import datetime
from typing import List

class Article(BaseModel):
    url: str
    title: str
    author: List[str] = []
    tags: List[str] = []
    date: str = str(datetime.now()) + " Autogenerated"